---

- name: get slave node secret
  uri:
    url: "http://{{ jenkins_master_ip }}:{{ jenkins_port }}/computer/{{ jenkins_slave_name }}/"
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
    return_content: yes
  register: webpage

- import_tasks: ../common/tasks/dependencies.yml
  when: "'secret' in webpage.content"
  
- import_tasks: run_slave_agent.yml
  when: "'secret' in webpage.content"
