---

- import_tasks: ../common/tasks/main.yml

- name: ensure jenkins user exists
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_slave_home }}"
    shell: /bin/bash
    state: present

- name: check if slave agent is running
  shell: "pgrep -f http://{{ jenkins_master_ip }}:{{ jenkins_port }}/computer/{{ jenkins_slave_name }}/slave-agent.jnlp"
  become: yes
  become_user: "{{ jenkins_user }}"
  register: slave_agent_pid
  ignore_errors: yes
  changed_when: false
  
- debug:
    var: slave_agent_pid

- import_tasks: run_slave_agent.yml
  when: slave_agent_pid.stdout is defined and
        slave_agent_pid.stdout == ""
