---

- name: ensure jenkins user exists
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_slave_home }}"
    shell: /bin/bash
    state: present

- name: ensure jenkins slave agent is in place
  get_url:
    url: "http://{{ jenkins_master_ip }}:{{ jenkins_port }}/jnlpJars/agent.jar"
    dest: "{{ jenkins_slave_home }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775

- name: ensure startup.sh script is in place
  template:
    src: startup.sh.j2
    dest: "{{ jenkins_slave_home }}/startup.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775

- name: ensure service file is in place
  template:
    src: jenkins-slave.serivce.j2
    dest: "/etc/systemd/system/{{ jenkins_slave_service_name }}.service"
    mode: 0644

- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: ensure jenkins slave service is enabled and running
  service:
    name: "{{ jenkins_slave_service_name }}"
    state: started
    enabled: yes
