---

- name: ensure jenkins user exists
  user:
    name: "{{ jenkins_user }}"
    home: "{{ jenkins_slave_home }}"
    shell: /bin/bash
    state: present

- name: ensure jenkins slave agent is in place
  get_url:
    url: "http://{{ jenkins_master_ip }}:{{ jenkins_port }}/jnlpJars/agent.jar"
    dest: "{{ jenkins_slave_home }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775

- name: ensure startup.sh script is in place
  template:
    src: startup.sh
    dest: "{{ jenkins_slave_home }}/startup.sh"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775

- name: run jenkins slave agent
  shell: "{{ jenkins_slave_home }}/startup.sh"
  become: yes
  become_user: "{{ jenkins_user }}"
