---

- name: ensure init scripts directory exists
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775
  when: jenkins_installation.changed

- name: copy basic security init script
  template:
    src: basic-security.groovy
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775
  when: jenkins_installation.changed
  register: jenkins_security_config

- name: copy users init script
  template:
    src: users.groovy
    path: "{{ jenkins_home }}/init.groovy.d/users.groovy"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775
  when: jenkins_users != ""

- name: configure users
  lineinfile:
    path: "{{ jenkins_home }}/init.groovy.d/users.groovy"
    insertafter: EOF
    line: "hudsonRealm.createAccount('{{ item.username }}', '{{ item.password }}')"
  with_items: "{{ jenkins_users }}"
  when: jenkins_users != ""
  register: jenkins_users_config

- name: set jenkins command line options
  lineinfile:
    path: "{{ jenkins_init_file }}"
    regexp: '^JENKINS_JAVA_OPTIONS=.*'
    line: JENKINS_JAVA_OPTIONS="{{ jenkins_java_opts }}"
  register: jenkins_command_line_options

- name: ensure node directory exists
  file:
    path: "{{ jenkins_home }}/nodes/{{ jenkins_slave_name }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0775
  
- name: configure {{ jenkins_slave_name }} node
  template:
    src: config.xml
    path: "{{ jenkins_home }}/nodes/{{ jenkins_slave_name }}/config.xml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: 0664
  register: jenkins_node_config

- name: restart jenkins to apply changes
  service:
    name: jenkins
    state: restarted
  when: jenkins_security_config.changed or
        jenkins_users_config.changed or
        jenkins_command_line_options.changed or
        jenkins_node_config.changed

- import_tasks: wait-for-startup.yml

- name: remove jenkins security init scripts after first startup
  file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent

- name: remove jenkins users init scripts after first startup
  file:
    path: "{{ jenkins_home }}/init.groovy.d/users.groovy"
    state: absent
