---

- name: add jenkins repository to the yum repositories
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins repository gpg key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: install jenkins
  yum:
    name: jenkins
    state: latest
  register: jenkins_installation

- name: ensure jenkins is started and runs on startup
  service:
    name: jenkins
    state: started
    enabled: yes
