---

- name: wait for jenkins to start up
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_port }}/cli/"
    status_code: 200,403
    timeout: 5
  register: jenkins_webpage
  retries: 60
  delay: 5
  until: jenkins_webpage.status == 200 or
         jenkins_webpage.status == 403
